import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execute } from '../../scripts/cli.mjs';

test('covers the documented CLI command surface in an isolated data root', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'zhuiju-surface-'));
  const input = path.join(root, 'input.json');
  await fs.writeFile(input, JSON.stringify({ title: 'Surface', slug: 'surface' }));
  const add = await execute(['subscription', 'add', '--input', input], root);
  const id = add.data.id;
  assert.equal((await execute(['subscription', 'get', id], root)).ok, true);
  assert.equal((await execute(['subscription', 'update', id, '--input', input], root)).ok, true);
  assert.equal((await execute(['subscription', 'pause', id], root)).ok, true);
  assert.equal((await execute(['subscription', 'resume', id], root)).ok, true);
  await execute(['episode', 'ensure', id, 'main:1'], root);
  assert.equal((await execute(['episode', 'get', id, 'main:1'], root)).ok, true);
  assert.equal((await execute(['episode', 'list', id], root)).ok, true);
  assert.equal((await execute(['episode', 'missing', id], root)).ok, true);
  assert.equal((await execute(['episode', 'latest-missing', id], root)).ok, true);
  await assert.rejects(() => execute(['episode', 'mark-acquired', id, 'main:1'], root), /Media URL|validated/i);
  assert.equal((await execute(['media', 'list', id, 'main:1'], root)).ok, true);
  assert.equal((await execute(['media', 'validate', id, 'main:1'], root)).ok, true);
  assert.equal((await execute(['media', 'history', 'media_missing'], root)).ok, true);
  await execute(['task', 'enqueue', '--subscription', id, '--mode', 'manual', '--trigger', 'manual'], root);
  assert.equal((await execute(['task', 'status', id], root)).ok, true);
  await execute(['task', 'run', id], root);
  await execute(['task', 'complete', id], root);
  await execute(['task', 'enqueue', '--subscription', id, '--mode', 'manual', '--trigger', 'manual'], root);
  await execute(['task', 'pause', id], root);
  await execute(['task', 'enqueue', '--subscription', id, '--mode', 'manual', '--trigger', 'manual'], root);
  await execute(['task', 'cancel', id], root);
  assert.equal((await execute(['schedule', 'sync', id], root)).ok, true);
  assert.equal((await execute(['schedule', 'show', id], root)).ok, true);
  assert.equal((await execute(['schedule', 'remove', id], root)).ok, true);
  assert.equal((await execute(['runtime', 'detect'], root)).ok, true);
  assert.equal((await execute(['queue', 'status'], root)).ok, true);
  assert.equal((await execute(['doctor'], root)).ok, true);
  assert.equal((await execute(['migrate'], root)).ok, true);
  assert.equal((await execute(['subscription', 'remove', id], root)).data.removed, true);
});
